package projection

import (
	"debug/dwarf"
	"debug/elf"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"slices"
	"strings"

	"github.com/dantte-lp/goreveal/schema"
)

// BuildSourceTree projects recovered files into a minimal source tree.
func BuildSourceTree(analysis schema.Analysis, sourceFiles []string) (schema.SourceTree, error) {
	root := ""
	if analysis.BuildInfo != nil {
		root = analysis.BuildInfo.Path
	}
	if root == "" {
		return schema.SourceTree{}, errors.New("missing build info path for source tree projection")
	}

	seenModuleFiles := make(map[string]struct{})
	files := make([]string, 0, len(sourceFiles))
	externalFiles := make([]string, 0, len(sourceFiles))
	seenExternalFiles := make(map[string]struct{})
	for _, file := range sourceFiles {
		if file == "" || file == "<autogenerated>" {
			continue
		}
		if !strings.HasPrefix(file, root+"/") {
			if _, ok := seenExternalFiles[file]; !ok {
				seenExternalFiles[file] = struct{}{}
				externalFiles = append(externalFiles, file)
			}
			continue
		}
		rel := strings.TrimPrefix(file, root+"/")
		if rel == "" {
			continue
		}
		if _, ok := seenModuleFiles[rel]; ok {
			continue
		}
		seenModuleFiles[rel] = struct{}{}
		files = append(files, rel)
	}

	slices.Sort(files)
	slices.Sort(externalFiles)
	packages := buildPackages(root, files, analysis.Packages)
	externalPackages := buildExternalPackages(externalFiles)

	return schema.SourceTree{
		Root:             root,
		Files:            files,
		Packages:         packages,
		ExternalPackages: externalPackages,
	}, nil
}

// BuildFallbackSourceTree projects the minimal truthful source-tree view when
// source file evidence is unavailable but build info and module-local packages exist.
func BuildFallbackSourceTree(analysis schema.Analysis) (schema.SourceTree, error) {
	root := ""
	if analysis.BuildInfo != nil {
		root = analysis.BuildInfo.Path
	}
	if root == "" {
		return schema.SourceTree{}, errors.New("missing build info path for source tree projection")
	}

	packages, externalPackages := buildFallbackPackages(root, analysis.Packages)
	return schema.SourceTree{
		Root:             root,
		Files:            []string{},
		Packages:         packages,
		ExternalPackages: externalPackages,
	}, nil
}

// ReadSourceFiles extracts unique DWARF file paths from an ELF binary.
func ReadSourceFiles(pathname string) ([]string, error) {
	fh, err := os.Open(pathname)
	if err != nil {
		return nil, fmt.Errorf("open file: %w", err)
	}
	defer fh.Close()

	ef, err := elf.NewFile(fh)
	if err != nil {
		return nil, fmt.Errorf("open ELF: %w", err)
	}

	data, err := ef.DWARF()
	if err != nil {
		return nil, fmt.Errorf("load DWARF: %w", err)
	}

	reader := data.Reader()
	seen := make(map[string]struct{})
	files := make([]string, 0, 64)
	for {
		entry, err := reader.Next()
		if err != nil {
			return nil, fmt.Errorf("read DWARF entry: %w", err)
		}
		if entry == nil {
			break
		}
		if entry.Tag != dwarf.TagCompileUnit {
			continue
		}

		lineReader, err := data.LineReader(entry)
		if err != nil || lineReader == nil {
			continue
		}

		var line dwarf.LineEntry
		for {
			err := lineReader.Next(&line)
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				return nil, fmt.Errorf("read line table: %w", err)
			}
			if line.EndSequence || line.File == nil || line.File.Name == "" {
				continue
			}
			if _, ok := seen[line.File.Name]; ok {
				continue
			}
			seen[line.File.Name] = struct{}{}
			files = append(files, line.File.Name)
		}
	}

	slices.Sort(files)
	return files, nil
}

func buildPackages(root string, files []string, recovered []schema.Package) []schema.SourcePackage {
	recoveredByName := make(map[string]schema.Package, len(recovered))
	for _, pkg := range recovered {
		recoveredByName[pkg.Name] = pkg
	}

	byImportPath := make(map[string]*schema.SourcePackage, len(files))
	for _, file := range files {
		dir := path.Dir(file)
		if dir == "." {
			dir = ""
		}

		importPath, name, functionCount := sourcePackageMetadata(root, dir, recoveredByName)

		pkg, ok := byImportPath[importPath]
		if !ok {
			pkg = &schema.SourcePackage{
				Name:            name,
				ImportPath:      importPath,
				FunctionCount:   functionCount,
				HasFileEvidence: true,
				Files:           make([]string, 0, 4),
			}
			byImportPath[importPath] = pkg
		}
		if functionCount > pkg.FunctionCount {
			pkg.FunctionCount = functionCount
		}
		pkg.Files = append(pkg.Files, file)
	}

	pkgs := make([]schema.SourcePackage, 0, len(byImportPath))
	for _, pkg := range byImportPath {
		slices.Sort(pkg.Files)
		pkgs = append(pkgs, *pkg)
	}

	slices.SortFunc(pkgs, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})

	return pkgs
}

func sourcePackageMetadata(root, dir string, recovered map[string]schema.Package) (string, string, int) {
	importPath := root
	name := path.Base(root)
	if dir != "" {
		importPath = root + "/" + dir
		name = path.Base(dir)
	}

	recoveredPkg := findRecoveredPackage(recovered, root, dir, importPath, name)
	if recoveredPkg == nil {
		return importPath, name, 0
	}
	if dir == "" && recoveredPkg.Name == "main" {
		name = "main"
	}

	return importPath, name, recoveredPkg.FunctionCount
}

func findRecoveredPackage(
	recovered map[string]schema.Package,
	root, dir, importPath, fallbackName string,
) *schema.Package {
	candidates := []string{importPath}
	if dir == "" {
		candidates = append(candidates, "main")
	} else {
		candidates = append(candidates, dir, fallbackName)
		if relativeImportPath, ok := strings.CutPrefix(importPath, root+"/"); ok {
			candidates = append(candidates, relativeImportPath)
		}
	}

	for _, candidate := range candidates {
		if candidate == "" {
			continue
		}
		if pkg, ok := recovered[candidate]; ok {
			pkgCopy := pkg
			return &pkgCopy
		}
	}

	return nil
}

func buildExternalPackages(files []string) []schema.SourcePackage {
	if len(files) == 0 {
		return nil
	}

	byImportPath := make(map[string]*schema.SourcePackage, len(files))
	for _, file := range files {
		importPath, name := classifyExternalPackage(file)

		pkg, ok := byImportPath[importPath]
		if !ok {
			pkg = &schema.SourcePackage{
				Name:            name,
				ImportPath:      importPath,
				HasFileEvidence: true,
				Files:           make([]string, 0, 4),
			}
			byImportPath[importPath] = pkg
		}
		pkg.Files = append(pkg.Files, file)
	}

	pkgs := make([]schema.SourcePackage, 0, len(byImportPath))
	for _, pkg := range byImportPath {
		slices.Sort(pkg.Files)
		pkgs = append(pkgs, *pkg)
	}

	slices.SortFunc(pkgs, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})

	return pkgs
}

func buildFallbackPackages(root string, recovered []schema.Package) ([]schema.SourcePackage, []schema.SourcePackage) {
	modulePackages := make([]schema.SourcePackage, 0, len(recovered))
	externalPackages := make([]schema.SourcePackage, 0, len(recovered))
	for _, pkg := range recovered {
		importPath := pkg.ImportPath
		if importPath == "" && pkg.Name == "main" {
			importPath = root
		}
		if importPath == "" {
			importPath = pkg.Name
		}
		if importPath == "" {
			continue
		}

		name := pkg.Name
		if name == "" {
			name = path.Base(importPath)
		}

		node := schema.SourcePackage{
			Name:            name,
			ImportPath:      importPath,
			FunctionCount:   pkg.FunctionCount,
			HasFileEvidence: false,
			Files:           []string{},
		}
		if pkg.ModuleLocal {
			modulePackages = append(modulePackages, node)
		} else {
			externalPackages = append(externalPackages, node)
		}
	}

	slices.SortFunc(modulePackages, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})
	slices.SortFunc(externalPackages, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})

	return modulePackages, externalPackages
}

func classifyExternalPackage(file string) (string, string) {
	dir := path.Dir(file)
	if idx := strings.Index(file, "/src/"); idx >= 0 {
		trimmed := strings.TrimPrefix(dir[idx+len("/src/"):], "/")
		if trimmed != "" && trimmed != "." {
			return trimmed, path.Base(trimmed)
		}
	}

	if dir == "." || dir == "/" {
		return file, path.Base(file)
	}

	return dir, path.Base(dir)
}
