package projection

import (
	"debug/dwarf"
	"debug/elf"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"slices"
	"strings"

	"github.com/dantte-lp/goreveal/schema"
)

// BuildSourceTree projects recovered files into a minimal source tree.
func BuildSourceTree(analysis schema.Analysis, sourceFiles []string) (schema.SourceTree, error) {
	root := ""
	if analysis.BuildInfo != nil {
		root = analysis.BuildInfo.Path
	}
	if root == "" {
		return schema.SourceTree{}, errors.New("missing build info path for source tree projection")
	}

	seenModuleFiles := make(map[string]struct{})
	files := make([]string, 0, len(sourceFiles))
	externalFiles := make([]string, 0, len(sourceFiles))
	seenExternalFiles := make(map[string]struct{})
	for _, file := range sourceFiles {
		if file == "" || file == "<autogenerated>" {
			continue
		}
		if !strings.HasPrefix(file, root+"/") {
			if _, ok := seenExternalFiles[file]; !ok {
				seenExternalFiles[file] = struct{}{}
				externalFiles = append(externalFiles, file)
			}
			continue
		}
		rel := strings.TrimPrefix(file, root+"/")
		if rel == "" {
			continue
		}
		if _, ok := seenModuleFiles[rel]; ok {
			continue
		}
		seenModuleFiles[rel] = struct{}{}
		files = append(files, rel)
	}

	slices.Sort(files)
	slices.Sort(externalFiles)
	packages := buildPackages(root, files, analysis.Packages)
	externalPackages := buildExternalPackages(externalFiles, schema.SourceEvidenceKindDWARFPaths)

	return schema.SourceTree{
		Root:               root,
		SourceEvidenceKind: schema.SourceEvidenceKindDWARFPaths,
		SourceEvidenceSummary: summarizeSourceEvidence(
			schema.SourceEvidenceKindDWARFPaths,
			packages,
			externalPackages,
		),
		Files:            files,
		Packages:         packages,
		ExternalPackages: externalPackages,
	}, nil
}

// BuildFallbackSourceTree projects the minimal truthful source-tree view when
// source file evidence is unavailable but build info and module-local packages exist.
func BuildFallbackSourceTree(analysis schema.Analysis) (schema.SourceTree, error) {
	root := ""
	if analysis.BuildInfo != nil {
		root = analysis.BuildInfo.Path
	}
	if root == "" {
		return schema.SourceTree{}, errors.New("missing build info path for source tree projection")
	}

	packages, externalPackages := buildFallbackPackages(root, analysis.Packages)
	return schema.SourceTree{
		Root:               root,
		SourceEvidenceKind: schema.SourceEvidenceKindPackageFallback,
		SourceEvidenceSummary: summarizeSourceEvidence(
			schema.SourceEvidenceKindPackageFallback,
			packages,
			externalPackages,
		),
		Files:            []string{},
		Packages:         packages,
		ExternalPackages: externalPackages,
	}, nil
}

// BuildFunctionSourceTree projects a bounded source-like tree from recovered
// function source_file metadata when richer DWARF-backed file evidence is unavailable.
func BuildFunctionSourceTree(analysis schema.Analysis) (schema.SourceTree, error) {
	root := ""
	if analysis.BuildInfo != nil {
		root = analysis.BuildInfo.Path
	}
	if root == "" {
		return schema.SourceTree{}, errors.New("missing build info path for source tree projection")
	}
	if len(analysis.Functions) == 0 {
		return schema.SourceTree{}, errors.New("missing functions for source tree projection")
	}

	moduleByImportPath := map[string]*schema.SourcePackage{}
	externalByImportPath := map[string]*schema.SourcePackage{}
	moduleFilesSeen := map[string]struct{}{}
	moduleFiles := make([]string, 0, 16)

	for _, fn := range analysis.Functions {
		if fn.SourceFile == "" || fn.SourceFile == "<autogenerated>" {
			continue
		}

		importPath := fn.ImportPath
		if importPath == "" && fn.ModuleLocal && fn.Package == "main" {
			importPath = root
		}
		if importPath == "" {
			continue
		}

		name := fn.Package
		if name == "" {
			name = path.Base(importPath)
		}

		target := externalByImportPath
		if fn.ModuleLocal {
			target = moduleByImportPath
		}

		pkg, ok := target[importPath]
		if !ok {
			pkg = &schema.SourcePackage{
				Name:               name,
				ImportPath:         importPath,
				HasFileEvidence:    true,
				SourceEvidenceKind: schema.SourceEvidenceKindLineTableFiles,
				Files:              make([]string, 0, 4),
			}
			target[importPath] = pkg
		}
		if fn.End > fn.Entry {
			pkg.FunctionCount++
		}
		if !slices.Contains(pkg.Files, fn.SourceFile) {
			pkg.Files = append(pkg.Files, fn.SourceFile)
		}
		if fn.ModuleLocal {
			if _, ok := moduleFilesSeen[fn.SourceFile]; !ok {
				moduleFilesSeen[fn.SourceFile] = struct{}{}
				moduleFiles = append(moduleFiles, fn.SourceFile)
			}
		}
	}

	if len(moduleByImportPath) == 0 && len(externalByImportPath) == 0 {
		return schema.SourceTree{}, errors.New("missing line-table-backed source file evidence")
	}

	modulePackages := sourcePackagesFromMap(moduleByImportPath)
	externalPackages := sourcePackagesFromMap(externalByImportPath)
	slices.Sort(moduleFiles)

	return schema.SourceTree{
		Root:               root,
		SourceEvidenceKind: schema.SourceEvidenceKindLineTableFiles,
		SourceEvidenceSummary: summarizeSourceEvidence(
			schema.SourceEvidenceKindLineTableFiles,
			modulePackages,
			externalPackages,
		),
		PathlessFileEvidence: true,
		Files:                moduleFiles,
		Packages:             modulePackages,
		ExternalPackages:     externalPackages,
	}, nil
}

// ReadSourceFiles extracts unique DWARF file paths from an ELF binary.
func ReadSourceFiles(pathname string) ([]string, error) {
	fh, err := os.Open(pathname)
	if err != nil {
		return nil, fmt.Errorf("open file: %w", err)
	}
	defer fh.Close()

	ef, err := elf.NewFile(fh)
	if err != nil {
		return nil, fmt.Errorf("open ELF: %w", err)
	}

	data, err := ef.DWARF()
	if err != nil {
		return nil, fmt.Errorf("load DWARF: %w", err)
	}

	reader := data.Reader()
	seen := make(map[string]struct{})
	files := make([]string, 0, 64)
	for {
		entry, err := reader.Next()
		if err != nil {
			return nil, fmt.Errorf("read DWARF entry: %w", err)
		}
		if entry == nil {
			break
		}
		if entry.Tag != dwarf.TagCompileUnit {
			continue
		}

		lineReader, err := data.LineReader(entry)
		if err != nil || lineReader == nil {
			continue
		}

		var line dwarf.LineEntry
		for {
			err := lineReader.Next(&line)
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				return nil, fmt.Errorf("read line table: %w", err)
			}
			if line.EndSequence || line.File == nil || line.File.Name == "" {
				continue
			}
			if _, ok := seen[line.File.Name]; ok {
				continue
			}
			seen[line.File.Name] = struct{}{}
			files = append(files, line.File.Name)
		}
	}

	slices.Sort(files)
	return files, nil
}

func buildPackages(root string, files []string, recovered []schema.Package) []schema.SourcePackage {
	recoveredByName := make(map[string]schema.Package, len(recovered))
	for _, pkg := range recovered {
		recoveredByName[pkg.Name] = pkg
	}

	byImportPath := make(map[string]*schema.SourcePackage, len(files))
	for _, file := range files {
		dir := path.Dir(file)
		if dir == "." {
			dir = ""
		}

		importPath, name, functionCount := sourcePackageMetadata(root, dir, recoveredByName)

		pkg, ok := byImportPath[importPath]
		if !ok {
			pkg = &schema.SourcePackage{
				Name:               name,
				ImportPath:         importPath,
				FunctionCount:      functionCount,
				HasFileEvidence:    true,
				SourceEvidenceKind: schema.SourceEvidenceKindDWARFPaths,
				Files:              make([]string, 0, 4),
			}
			byImportPath[importPath] = pkg
		}
		if functionCount > pkg.FunctionCount {
			pkg.FunctionCount = functionCount
		}
		pkg.Files = append(pkg.Files, file)
	}

	pkgs := make([]schema.SourcePackage, 0, len(byImportPath))
	for _, pkg := range byImportPath {
		slices.Sort(pkg.Files)
		pkgs = append(pkgs, *pkg)
	}

	slices.SortFunc(pkgs, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})

	return pkgs
}

func sourcePackageMetadata(root, dir string, recovered map[string]schema.Package) (string, string, int) {
	importPath := root
	name := path.Base(root)
	if dir != "" {
		importPath = root + "/" + dir
		name = path.Base(dir)
	}

	recoveredPkg := findRecoveredPackage(recovered, root, dir, importPath, name)
	if recoveredPkg == nil {
		return importPath, name, 0
	}
	if dir == "" && recoveredPkg.Name == "main" {
		name = "main"
	}

	return importPath, name, recoveredPkg.FunctionCount
}

func findRecoveredPackage(
	recovered map[string]schema.Package,
	root, dir, importPath, fallbackName string,
) *schema.Package {
	candidates := []string{importPath}
	if dir == "" {
		candidates = append(candidates, "main")
	} else {
		candidates = append(candidates, dir, fallbackName)
		if relativeImportPath, ok := strings.CutPrefix(importPath, root+"/"); ok {
			candidates = append(candidates, relativeImportPath)
		}
	}

	for _, candidate := range candidates {
		if candidate == "" {
			continue
		}
		if pkg, ok := recovered[candidate]; ok {
			pkgCopy := pkg
			return &pkgCopy
		}
	}

	return nil
}

func buildExternalPackages(files []string, evidenceKind schema.SourceEvidenceKind) []schema.SourcePackage {
	if len(files) == 0 {
		return nil
	}

	byImportPath := make(map[string]*schema.SourcePackage, len(files))
	for _, file := range files {
		importPath, name := classifyExternalPackage(file)

		pkg, ok := byImportPath[importPath]
		if !ok {
			pkg = &schema.SourcePackage{
				Name:               name,
				ImportPath:         importPath,
				HasFileEvidence:    true,
				SourceEvidenceKind: evidenceKind,
				Files:              make([]string, 0, 4),
			}
			byImportPath[importPath] = pkg
		}
		pkg.Files = append(pkg.Files, file)
	}

	pkgs := make([]schema.SourcePackage, 0, len(byImportPath))
	for _, pkg := range byImportPath {
		slices.Sort(pkg.Files)
		pkgs = append(pkgs, *pkg)
	}

	slices.SortFunc(pkgs, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})

	return pkgs
}

func buildFallbackPackages(root string, recovered []schema.Package) ([]schema.SourcePackage, []schema.SourcePackage) {
	modulePackages := make([]schema.SourcePackage, 0, len(recovered))
	externalPackages := make([]schema.SourcePackage, 0, len(recovered))
	for _, pkg := range recovered {
		importPath := pkg.ImportPath
		if importPath == "" && pkg.Name == "main" {
			importPath = root
		}
		if importPath == "" {
			importPath = pkg.Name
		}
		if importPath == "" {
			continue
		}

		name := pkg.Name
		if name == "" {
			name = path.Base(importPath)
		}

		node := schema.SourcePackage{
			Name:               name,
			ImportPath:         importPath,
			FunctionCount:      pkg.FunctionCount,
			HasFileEvidence:    false,
			SourceEvidenceKind: schema.SourceEvidenceKindPackageFallback,
			Files:              []string{},
		}
		if pkg.ModuleLocal {
			modulePackages = append(modulePackages, node)
		} else {
			externalPackages = append(externalPackages, node)
		}
	}

	slices.SortFunc(modulePackages, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})
	slices.SortFunc(externalPackages, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})

	return modulePackages, externalPackages
}

func summarizeSourceEvidence(
	treeKind schema.SourceEvidenceKind,
	packages []schema.SourcePackage,
	externalPackages []schema.SourcePackage,
) schema.SourceEvidenceSummary {
	summary := schema.SourceEvidenceSummary{TreeKind: treeKind}
	seenKinds := make(map[schema.SourceEvidenceKind]struct{}, 3)

	for _, pkg := range packages {
		incrementSourceEvidenceCount(&summary, pkg.SourceEvidenceKind)
		incrementSourceEvidenceFiles(&summary, pkg.SourceEvidenceKind, len(pkg.Files))
		if pkg.SourceEvidenceKind != "" {
			seenKinds[pkg.SourceEvidenceKind] = struct{}{}
		}
	}
	for _, pkg := range externalPackages {
		incrementSourceEvidenceCount(&summary, pkg.SourceEvidenceKind)
		incrementSourceEvidenceFiles(&summary, pkg.SourceEvidenceKind, len(pkg.Files))
		if pkg.SourceEvidenceKind != "" {
			seenKinds[pkg.SourceEvidenceKind] = struct{}{}
		}
	}

	summary.MixedPackageEvidenceKinds = len(seenKinds) > 1
	return summary
}

func incrementSourceEvidenceCount(summary *schema.SourceEvidenceSummary, kind schema.SourceEvidenceKind) {
	switch kind {
	case schema.SourceEvidenceKindDWARFPaths:
		summary.DWARFPathPackageCount++
	case schema.SourceEvidenceKindLineTableFiles:
		summary.LineTablePackageCount++
	case schema.SourceEvidenceKindPackageFallback:
		summary.PackageFallbackPackageCount++
	}
}

func incrementSourceEvidenceFiles(summary *schema.SourceEvidenceSummary, kind schema.SourceEvidenceKind, fileCount int) {
	switch kind {
	case schema.SourceEvidenceKindDWARFPaths:
		summary.DWARFPathFileCount += fileCount
	case schema.SourceEvidenceKindLineTableFiles:
		summary.LineTableFileCount += fileCount
	case schema.SourceEvidenceKindPackageFallback:
		summary.PackageFallbackFileCount += fileCount
	}
}

func sourcePackagesFromMap(byImportPath map[string]*schema.SourcePackage) []schema.SourcePackage {
	pkgs := make([]schema.SourcePackage, 0, len(byImportPath))
	for _, pkg := range byImportPath {
		slices.Sort(pkg.Files)
		pkgs = append(pkgs, *pkg)
	}
	slices.SortFunc(pkgs, func(a, b schema.SourcePackage) int {
		if a.ImportPath < b.ImportPath {
			return -1
		}
		if a.ImportPath > b.ImportPath {
			return 1
		}
		return 0
	})
	return pkgs
}

func classifyExternalPackage(file string) (string, string) {
	dir := path.Dir(file)
	if idx := strings.Index(dir, "/src/"); idx >= 0 {
		trimmed := strings.TrimPrefix(dir[idx+len("/src/"):], "/")
		if trimmed != "" && trimmed != "." {
			return trimmed, path.Base(trimmed)
		}
	}

	if dir == "." || dir == "/" {
		return file, path.Base(file)
	}

	return dir, path.Base(dir)
}
