package functions

import (
	"errors"
	"testing"

	"github.com/dantte-lp/goreveal/core/recoveryerr"
)

func TestRecoverFixture(t *testing.T) {
	t.Parallel()

	funcs, err := Recover("../../corpus/fixtures/go-elf-buildinfo-linux-amd64/fixture.bin")
	if err != nil {
		t.Fatalf("Recover() error = %v", err)
	}

	if len(funcs) == 0 {
		t.Fatal("Recover() returned no functions")
	}

	for _, want := range []string{"main.main", "main.helperAdd", "main.helperBanner"} {
		if !containsFunction(funcs, want) {
			t.Fatalf("Recover() missing function %q", want)
		}
	}

	mainFn, ok := findFunction(funcs, "main.main")
	if !ok {
		t.Fatal("Recover() missing main.main for metadata assertions")
	}
	if mainFn.Package != "main" {
		t.Fatalf("main.main package = %q, want %q", mainFn.Package, "main")
	}
	if mainFn.ImportPath != "" {
		t.Fatalf("main.main import path = %q, want empty", mainFn.ImportPath)
	}
	if mainFn.SourceFile != "main.go" {
		t.Fatalf("main.main source file = %q, want %q", mainFn.SourceFile, "main.go")
	}
	if mainFn.SourceLine != 34 {
		t.Fatalf("main.main source line = %d, want %d", mainFn.SourceLine, 34)
	}

	runtimeFn, ok := findFunction(funcs, "runtime.newobject")
	if !ok {
		t.Fatal("Recover() missing runtime.newobject for metadata assertions")
	}
	if runtimeFn.Package != "runtime" {
		t.Fatalf("runtime.newobject package = %q, want %q", runtimeFn.Package, "runtime")
	}
	if runtimeFn.ImportPath != "runtime" {
		t.Fatalf("runtime.newobject import path = %q, want %q", runtimeFn.ImportPath, "runtime")
	}
	if runtimeFn.SourceFile == "" {
		t.Fatal("runtime.newobject source file is empty, want bounded file truth from pclntab line table")
	}
	if runtimeFn.SourceLine == 0 {
		t.Fatal("runtime.newobject source line is zero, want bounded line truth from pclntab line table")
	}

	autoFn, ok := findFunction(funcs, "type:.eq.internal/abi.UncommonType")
	if !ok {
		t.Fatal("Recover() missing autogenerated function for metadata assertions")
	}
	if autoFn.SourceFile != "<autogenerated>" {
		t.Fatalf("autogenerated source file = %q, want %q", autoFn.SourceFile, "<autogenerated>")
	}
	if !autoFn.Autogenerated {
		t.Fatal("autogenerated function marker = false, want true")
	}
}

func TestRecoverMachOFixture(t *testing.T) {
	t.Parallel()

	funcs, err := Recover("../../corpus/fixtures/go-macho-buildinfo-darwin-amd64/fixture.bin")
	if err != nil {
		t.Fatalf("Recover() error = %v", err)
	}

	if len(funcs) == 0 {
		t.Fatal("Recover() returned no functions")
	}

	for _, want := range []string{"main.main", "main.helperAdd", "main.helperBanner"} {
		if !containsFunction(funcs, want) {
			t.Fatalf("Recover() missing function %q", want)
		}
	}

	mainFn, ok := findFunction(funcs, "main.main")
	if !ok {
		t.Fatal("Recover() missing main.main for metadata assertions")
	}
	if mainFn.Package != "main" {
		t.Fatalf("main.main package = %q, want %q", mainFn.Package, "main")
	}
	if mainFn.SourceFile != "main.go" {
		t.Fatalf("main.main source file = %q, want %q", mainFn.SourceFile, "main.go")
	}
	if mainFn.SourceLine == 0 {
		t.Fatalf("main.main source line = %d, want non-zero", mainFn.SourceLine)
	}
}

func TestRecoverPEFixture(t *testing.T) {
	t.Parallel()

	funcs, err := Recover("../../corpus/fixtures/go-pe-buildinfo-windows-amd64/fixture.exe")
	if err != nil {
		t.Fatalf("Recover() error = %v", err)
	}

	if len(funcs) == 0 {
		t.Fatal("Recover() returned no functions")
	}

	for _, want := range []string{"main.main", "main.helperAdd", "main.helperBanner"} {
		if !containsFunction(funcs, want) {
			t.Fatalf("Recover() missing function %q", want)
		}
	}

	mainFn, ok := findFunction(funcs, "main.main")
	if !ok {
		t.Fatal("Recover() missing main.main for metadata assertions")
	}
	if mainFn.Package != "main" {
		t.Fatalf("main.main package = %q, want %q", mainFn.Package, "main")
	}
	if mainFn.SourceFile != "main.go" {
		t.Fatalf("main.main source file = %q, want %q", mainFn.SourceFile, "main.go")
	}
	if mainFn.SourceLine == 0 {
		t.Fatalf("main.main source line = %d, want non-zero", mainFn.SourceLine)
	}
}

func TestRecoverNonGoELFIsUnavailable(t *testing.T) {
	t.Parallel()

	_, err := Recover("/bin/sh")
	if !errors.Is(err, recoveryerr.ErrUnavailable) {
		t.Fatalf("Recover(/bin/sh) error = %v, want unavailable", err)
	}
}

func containsFunction(funcs []Function, want string) bool {
	for _, fn := range funcs {
		if fn.Name == want && fn.Entry != 0 {
			return true
		}
	}
	return false
}

func findFunction(funcs []Function, want string) (Function, bool) {
	for _, fn := range funcs {
		if fn.Name == want {
			return fn, true
		}
	}

	return Function{}, false
}
