package functions

import (
	"debug/gosym"
	"fmt"
	"path"
	"slices"
	"strings"

	"github.com/dantte-lp/goreveal/core/pclntab"
	"github.com/dantte-lp/goreveal/schema"
)

// Function is the canonical recovered function representation.
type Function = schema.Function

// Recover extracts functions from a supported Go binary via pclntab.
func Recover(path string) ([]Function, error) {
	data, err := pclntab.Read(path)
	if err != nil {
		return nil, fmt.Errorf("read pclntab: %w", err)
	}

	table, err := gosym.NewTable(data.Symtab, gosym.NewLineTable(data.PCLN, data.TextStart))
	if err != nil {
		return nil, fmt.Errorf("build gosym table: %w", err)
	}

	funcs := make([]Function, 0, len(table.Funcs))
	for _, fn := range table.Funcs {
		if fn.Name == "" || fn.Entry == 0 {
			continue
		}
		pkg, ok := packageName(fn.Name)
		importPath := ""
		if ok && pkg != "main" {
			importPath = pkg
		}
		sourceFile, sourceLine, _ := table.PCToLine(fn.Entry)
		normalizedSourceFile := normalizeSourceFile(sourceFile)
		funcs = append(funcs, Function{
			Name:          fn.Name,
			Package:       pkg,
			ImportPath:    importPath,
			SourceFile:    normalizedSourceFile,
			SourceLine:    sourceLine,
			Autogenerated: normalizedSourceFile == "<autogenerated>",
			Entry:         fn.Entry,
			End:           fn.End,
			Provenance: schema.Provenance{
				Source:     "core.functions.pclntab",
				Confidence: "high",
			},
		})
	}

	slices.SortFunc(funcs, func(a, b Function) int {
		switch {
		case a.Entry < b.Entry:
			return -1
		case a.Entry > b.Entry:
			return 1
		default:
			switch {
			case a.Name < b.Name:
				return -1
			case a.Name > b.Name:
				return 1
			default:
				return 0
			}
		}
	})

	return funcs, nil
}

// EnrichBuildInfoMetadata adds bounded module-local function metadata.
func EnrichBuildInfoMetadata(funcs []Function, info *schema.BuildInfo) []Function {
	if info == nil || info.Path == "" {
		return funcs
	}

	out := make([]Function, len(funcs))
	copy(out, funcs)

	for i := range out {
		if out[i].Package == "" {
			continue
		}

		importPath := out[i].ImportPath
		if out[i].Package == "main" {
			importPath = info.Path
		}
		if importPath == "" {
			continue
		}

		out[i].ImportPath = importPath
		out[i].ModuleLocal = importPath == info.Path || strings.HasPrefix(importPath, info.Path+"/")
	}

	return out
}

func packageName(functionName string) (string, bool) {
	if strings.HasPrefix(functionName, "type:") {
		return "", false
	}

	lastSlash := strings.LastIndex(functionName, "/")
	searchStart := max(lastSlash+1, 0)

	dot := strings.Index(functionName[searchStart:], ".")
	if dot <= 0 {
		return "", false
	}

	name := functionName[:searchStart+dot]
	if name == "" {
		return "", false
	}

	return name, true
}

func normalizeSourceFile(file string) string {
	if file == "" {
		return ""
	}

	base := path.Base(file)
	if base == "." || base == "/" {
		return ""
	}

	return base
}
