package schema

import "encoding/json"

const IDAExportContractV1 = "goreveal.export.ida/v1"

// IDAExport is the stable v1 payload for thin IDA-side consumers.
type IDAExport struct {
	Contract   string           `json:"contract"`
	Input      Input            `json:"input"`
	BuildInfo  *BuildInfo       `json:"build_info,omitempty"`
	Runtime    *RuntimeMetadata `json:"runtime,omitempty"`
	Peeling    *PeelingAnalysis `json:"peeling,omitempty"`
	Functions  []IDAFunction    `json:"functions,omitempty"`
	Packages   []Package        `json:"packages,omitempty"`
	Types      []IDAType        `json:"types,omitempty"`
	Strings    []IDAString      `json:"strings,omitempty"`
	SourceTree *SourceTree      `json:"source_tree,omitempty"`
	Refined    *RefinedSummary  `json:"refined,omitempty"`
}

// IDAFunction carries one function plus its refined display name.
type IDAFunction struct {
	Name          string     `json:"name"`
	RefinedName   string     `json:"refined_name,omitempty"`
	Package       string     `json:"package,omitempty"`
	ImportPath    string     `json:"import_path,omitempty"`
	SourceFile    string     `json:"source_file,omitempty"`
	SourceLine    int        `json:"source_line,omitempty"`
	Autogenerated bool       `json:"autogenerated,omitempty"`
	Entry         uint64     `json:"entry"`
	End           uint64     `json:"end"`
	ModuleLocal   bool       `json:"module_local,omitempty"`
	Provenance    Provenance `json:"provenance"`
}

// IDAType carries one type plus its refined display name.
type IDAType struct {
	Name            string     `json:"name"`
	RefinedName     string     `json:"refined_name,omitempty"`
	Package         string     `json:"package,omitempty"`
	ImportPath      string     `json:"import_path,omitempty"`
	Kind            string     `json:"kind"`
	SourceFileCount int        `json:"source_file_count,omitempty"`
	ModuleLocal     bool       `json:"module_local,omitempty"`
	UserMeaningful  bool       `json:"user_meaningful,omitempty"`
	Provenance      Provenance `json:"provenance"`
}

// IDAString carries one recovered string plus its refined display value.
type IDAString struct {
	Value        string     `json:"value"`
	RefinedValue string     `json:"refined_value,omitempty"`
	Region       string     `json:"region"`
	Address      uint64     `json:"address,omitempty"`
	Offset       uint64     `json:"offset"`
	Provenance   Provenance `json:"provenance"`
}

// RefinedSummary keeps the lightweight refined layer visible to export consumers.
type RefinedSummary struct {
	Passes []string `json:"passes,omitempty"`
}

// MarshalJSON freezes IDAExport to the v1 wire graph instead of serializing
// mutable canonical schema structs directly.
func (export IDAExport) MarshalJSON() ([]byte, error) {
	return json.Marshal(newIDAExportV1Wire(export))
}

// NewIDAExport maps canonical analysis into the stable IDA-oriented payload.
func NewIDAExport(analysis Analysis) IDAExport {
	out := IDAExport{
		Contract:   IDAExportContractV1,
		Input:      analysis.Input,
		BuildInfo:  analysis.BuildInfo,
		Runtime:    analysis.Runtime,
		Peeling:    analysis.Peeling,
		Packages:   analysis.Packages,
		SourceTree: analysis.SourceTree,
	}
	if analysis.Refined != nil {
		out.Refined = &RefinedSummary{Passes: append([]string(nil), analysis.Refined.Passes...)}
	}

	for i, fn := range analysis.Functions {
		exported := newIDAFunction(fn)
		if analysis.Refined != nil && i < len(analysis.Refined.Functions) {
			exported.RefinedName = analysis.Refined.Functions[i].Name
		}
		out.Functions = append(out.Functions, exported)
	}

	for i, typ := range analysis.Types {
		exported := newIDAType(typ)
		if analysis.Refined != nil && i < len(analysis.Refined.Types) {
			exported.RefinedName = analysis.Refined.Types[i].Name
		}
		out.Types = append(out.Types, exported)
	}

	for i, str := range analysis.Strings {
		exported := newIDAString(str)
		if analysis.Refined != nil && i < len(analysis.Refined.Strings) {
			exported.RefinedValue = analysis.Refined.Strings[i].Value
		}
		out.Strings = append(out.Strings, exported)
	}

	return out
}

func newIDAFunction(fn Function) IDAFunction {
	return IDAFunction{
		Name:          fn.Name,
		Package:       fn.Package,
		ImportPath:    fn.ImportPath,
		SourceFile:    fn.SourceFile,
		SourceLine:    fn.SourceLine,
		Autogenerated: fn.Autogenerated,
		Entry:         fn.Entry,
		End:           fn.End,
		ModuleLocal:   fn.ModuleLocal,
		Provenance:    fn.Provenance,
	}
}

func newIDAType(typ Type) IDAType {
	return IDAType{
		Name:            typ.Name,
		Package:         typ.Package,
		ImportPath:      typ.ImportPath,
		Kind:            typ.Kind,
		SourceFileCount: typ.SourceFileCount,
		ModuleLocal:     typ.ModuleLocal,
		UserMeaningful:  typ.UserMeaningful,
		Provenance:      typ.Provenance,
	}
}

func newIDAString(str StringCandidate) IDAString {
	return IDAString{
		Value:      str.Value,
		Region:     str.Region,
		Address:    str.Addr,
		Offset:     str.Offset,
		Provenance: str.Provenance,
	}
}
