package schema

const GhidraExportContractV1 = "goreveal.export.ghidra/v1"

// GhidraExport is the stable v1 payload for thin Ghidra-side consumers.
type GhidraExport struct {
	Contract   string           `json:"contract"`
	Program    GhidraProgram    `json:"program"`
	Runtime    *RuntimeMetadata `json:"runtime,omitempty"`
	Peeling    *PeelingAnalysis `json:"peeling,omitempty"`
	Symbols    []GhidraSymbol   `json:"symbols,omitempty"`
	Packages   []Package        `json:"packages,omitempty"`
	Types      []GhidraType     `json:"types,omitempty"`
	Strings    []GhidraString   `json:"strings,omitempty"`
	SourceTree *SourceTree      `json:"source_tree,omitempty"`
	Refined    *RefinedSummary  `json:"refined,omitempty"`
}

// GhidraProgram contains the program-level identity for import.
type GhidraProgram struct {
	Path       string     `json:"path"`
	Format     string     `json:"format"`
	ModulePath string     `json:"module_path,omitempty"`
	GoVersion  string     `json:"go_version,omitempty"`
	Provenance Provenance `json:"provenance"`
}

// GhidraSymbol carries one recovered symbol plus its refined display name.
type GhidraSymbol struct {
	Name          string     `json:"name"`
	RefinedName   string     `json:"refined_name,omitempty"`
	Package       string     `json:"package,omitempty"`
	ImportPath    string     `json:"import_path,omitempty"`
	SourceFile    string     `json:"source_file,omitempty"`
	SourceLine    int        `json:"source_line,omitempty"`
	Autogenerated bool       `json:"autogenerated,omitempty"`
	Address       uint64     `json:"address"`
	End           uint64     `json:"end"`
	ModuleLocal   bool       `json:"module_local,omitempty"`
	Provenance    Provenance `json:"provenance"`
}

// GhidraType carries one recovered type plus its refined display name.
type GhidraType struct {
	Name            string     `json:"name"`
	RefinedName     string     `json:"refined_name,omitempty"`
	Package         string     `json:"package,omitempty"`
	ImportPath      string     `json:"import_path,omitempty"`
	Kind            string     `json:"kind"`
	SourceFileCount int        `json:"source_file_count,omitempty"`
	ModuleLocal     bool       `json:"module_local,omitempty"`
	UserMeaningful  bool       `json:"user_meaningful,omitempty"`
	Provenance      Provenance `json:"provenance"`
}

// GhidraString carries one recovered string plus its refined display value.
type GhidraString struct {
	Value        string     `json:"value"`
	RefinedValue string     `json:"refined_value,omitempty"`
	Region       string     `json:"region"`
	Address      uint64     `json:"address,omitempty"`
	Offset       uint64     `json:"offset"`
	Provenance   Provenance `json:"provenance"`
}

// NewGhidraExport maps canonical analysis into the stable Ghidra-oriented payload.
func NewGhidraExport(analysis Analysis) GhidraExport {
	out := GhidraExport{
		Contract:   GhidraExportContractV1,
		Program:    newGhidraProgram(analysis),
		Runtime:    analysis.Runtime,
		Peeling:    analysis.Peeling,
		Packages:   analysis.Packages,
		SourceTree: analysis.SourceTree,
	}
	if analysis.Refined != nil {
		out.Refined = &RefinedSummary{Passes: append([]string(nil), analysis.Refined.Passes...)}
	}

	for i, fn := range analysis.Functions {
		exported := newGhidraSymbol(fn)
		if analysis.Refined != nil && i < len(analysis.Refined.Functions) {
			exported.RefinedName = analysis.Refined.Functions[i].Name
		}
		out.Symbols = append(out.Symbols, exported)
	}

	for i, typ := range analysis.Types {
		exported := newGhidraType(typ)
		if analysis.Refined != nil && i < len(analysis.Refined.Types) {
			exported.RefinedName = analysis.Refined.Types[i].Name
		}
		out.Types = append(out.Types, exported)
	}

	for i, str := range analysis.Strings {
		exported := newGhidraString(str)
		if analysis.Refined != nil && i < len(analysis.Refined.Strings) {
			exported.RefinedValue = analysis.Refined.Strings[i].Value
		}
		out.Strings = append(out.Strings, exported)
	}

	return out
}

func newGhidraProgram(analysis Analysis) GhidraProgram {
	program := GhidraProgram{
		Path:   analysis.Input.Path,
		Format: analysis.Input.Format,
		Provenance: Provenance{
			Source:     "schema.export.ghidra",
			Confidence: "high",
		},
	}
	if analysis.BuildInfo != nil {
		program.ModulePath = analysis.BuildInfo.Path
		program.GoVersion = analysis.BuildInfo.GoVersion
	}

	return program
}

func newGhidraSymbol(fn Function) GhidraSymbol {
	return GhidraSymbol{
		Name:          fn.Name,
		Package:       fn.Package,
		ImportPath:    fn.ImportPath,
		SourceFile:    fn.SourceFile,
		SourceLine:    fn.SourceLine,
		Autogenerated: fn.Autogenerated,
		Address:       fn.Entry,
		End:           fn.End,
		ModuleLocal:   fn.ModuleLocal,
		Provenance:    fn.Provenance,
	}
}

func newGhidraType(typ Type) GhidraType {
	return GhidraType{
		Name:            typ.Name,
		Package:         typ.Package,
		ImportPath:      typ.ImportPath,
		Kind:            typ.Kind,
		SourceFileCount: typ.SourceFileCount,
		ModuleLocal:     typ.ModuleLocal,
		UserMeaningful:  typ.UserMeaningful,
		Provenance:      typ.Provenance,
	}
}

func newGhidraString(str StringCandidate) GhidraString {
	return GhidraString{
		Value:      str.Value,
		Region:     str.Region,
		Address:    str.Addr,
		Offset:     str.Offset,
		Provenance: str.Provenance,
	}
}
