package schema

import "testing"

func TestNewIDAExport(t *testing.T) {
	t.Parallel()

	analysis := Analysis{
		Input: Input{
			Path:   "/tmp/sample.bin",
			Format: "elf",
		},
		BuildInfo: &BuildInfo{
			GoVersion: "go1.26.1",
			Path:      "example.com/sample",
			Provenance: Provenance{
				Source:     "core.buildinfo",
				Confidence: "high",
			},
		},
		Functions: []Function{
			{
				Name:          "main.main",
				Package:       "main",
				ImportPath:    "example.com/sample",
				SourceFile:    "main.go",
				SourceLine:    34,
				Autogenerated: false,
				Entry:         0x1000,
				End:           0x1100,
				ModuleLocal:   true,
				Provenance: Provenance{
					Source:     "core.pclntab",
					Confidence: "high",
				},
			},
		},
		Types: []Type{
			{
				Name:            "main.fixtureCounter",
				Package:         "main",
				ImportPath:      "example.com/sample",
				Kind:            "struct",
				SourceFileCount: 1,
				ModuleLocal:     true,
				UserMeaningful:  true,
				Provenance: Provenance{
					Source:     "core.types",
					Confidence: "medium",
				},
			},
		},
		Strings: []StringCandidate{
			{
				Value:  "hello",
				Region: ".rodata",
				Addr:   0x2010,
				Offset: 16,
				Provenance: Provenance{
					Source:     "core.strings",
					Confidence: "medium",
				},
			},
		},
		Refined: &RefinedAnalysis{
			Functions: []RefinedFunction{{Name: "main.main"}},
			Types:     []RefinedType{{Name: "main.fixtureCounter"}},
			Strings:   []RefinedString{{Value: "hello"}},
		},
	}

	got := NewIDAExport(analysis)

	if got.Contract != IDAExportContractV1 {
		t.Fatalf("contract = %q, want %q", got.Contract, IDAExportContractV1)
	}
	if len(got.Functions) != 1 || got.Functions[0].RefinedName != "main.main" {
		t.Fatalf("functions = %#v", got.Functions)
	}
	if got.Functions[0].Provenance.Source != "core.pclntab" {
		t.Fatalf("function provenance = %#v", got.Functions[0].Provenance)
	}
	if got.Functions[0].Package != "main" || got.Functions[0].ImportPath != "example.com/sample" || got.Functions[0].SourceFile != "main.go" || got.Functions[0].SourceLine != 34 || !got.Functions[0].ModuleLocal {
		t.Fatalf("function metadata = %#v", got.Functions[0])
	}
	if len(got.Types) != 1 || got.Types[0].RefinedName != "main.fixtureCounter" {
		t.Fatalf("types = %#v", got.Types)
	}
	if got.Types[0].Package != "main" || got.Types[0].ImportPath != "example.com/sample" || got.Types[0].SourceFileCount != 1 || !got.Types[0].ModuleLocal || !got.Types[0].UserMeaningful {
		t.Fatalf("type metadata = %#v", got.Types[0])
	}
	if len(got.Strings) != 1 || got.Strings[0].RefinedValue != "hello" {
		t.Fatalf("strings = %#v", got.Strings)
	}
	if got.Strings[0].Address != 0x2010 {
		t.Fatalf("string address = %#v", got.Strings[0])
	}
}

func TestNewGhidraExport(t *testing.T) {
	t.Parallel()

	analysis := Analysis{
		Input: Input{
			Path:   "/tmp/sample.bin",
			Format: "elf",
		},
		BuildInfo: &BuildInfo{
			GoVersion: "go1.26.1",
			Path:      "example.com/sample",
		},
		Functions: []Function{
			{
				Name:          "main.main",
				Package:       "main",
				ImportPath:    "example.com/sample",
				SourceFile:    "main.go",
				SourceLine:    34,
				Autogenerated: false,
				Entry:         0x1000,
				End:           0x1100,
				ModuleLocal:   true,
				Provenance: Provenance{
					Source:     "core.pclntab",
					Confidence: "high",
				},
			},
		},
		Refined: &RefinedAnalysis{
			Functions: []RefinedFunction{{Name: "main.main"}},
		},
	}

	got := NewGhidraExport(analysis)

	if got.Contract != GhidraExportContractV1 {
		t.Fatalf("contract = %q, want %q", got.Contract, GhidraExportContractV1)
	}
	if got.Program.Path != "/tmp/sample.bin" {
		t.Fatalf("program path = %q", got.Program.Path)
	}
	if got.Program.ModulePath != "example.com/sample" {
		t.Fatalf("module path = %q", got.Program.ModulePath)
	}
	if len(got.Symbols) != 1 || got.Symbols[0].RefinedName != "main.main" {
		t.Fatalf("symbols = %#v", got.Symbols)
	}
	if got.Symbols[0].Address != 0x1000 {
		t.Fatalf("symbol address = %#v", got.Symbols[0])
	}
	if got.Symbols[0].Package != "main" || got.Symbols[0].ImportPath != "example.com/sample" || got.Symbols[0].SourceFile != "main.go" || got.Symbols[0].SourceLine != 34 || !got.Symbols[0].ModuleLocal {
		t.Fatalf("symbol metadata = %#v", got.Symbols[0])
	}
	analysis.Types = []Type{
		{
			Name:            "main.fixtureCounter",
			Package:         "main",
			ImportPath:      "example.com/sample",
			Kind:            "struct",
			SourceFileCount: 1,
			ModuleLocal:     true,
			UserMeaningful:  true,
			Provenance: Provenance{
				Source:     "core.types",
				Confidence: "medium",
			},
		},
	}
	got = NewGhidraExport(analysis)
	if len(got.Types) != 1 || got.Types[0].Package != "main" || got.Types[0].ImportPath != "example.com/sample" || got.Types[0].SourceFileCount != 1 || !got.Types[0].ModuleLocal || !got.Types[0].UserMeaningful {
		t.Fatalf("ghidra types = %#v", got.Types)
	}
	analysis.Strings = []StringCandidate{
		{
			Value:  "hello",
			Region: ".rodata",
			Addr:   0x2010,
			Offset: 16,
			Provenance: Provenance{
				Source:     "core.strings",
				Confidence: "medium",
			},
		},
	}
	got = NewGhidraExport(analysis)
	if len(got.Strings) != 1 || got.Strings[0].Address != 0x2010 {
		t.Fatalf("ghidra strings = %#v", got.Strings)
	}
}
